#################################################
# Config: Development                           #
#################################################
# (production settings go in _config.build.yml) #

#############
# Meta info #
#############

name: 'Be on the right side of history.'
description: ''

social_title: 'Be on the right side of history.'
social_description: ''
twittertext: 'Be on the right side of history. https://www.fightforthefuture.org/2017Pledge/'
signup_button_text: "Sign the pledge"

action_network_form: "https://actionnetwork.org/petitions/be-on-the-right-side-of-history/signatures"
action_network_petition_id: ""
action_network_source: "rockagainstthetpp"
action_network_tag_list:
- "pledge"
mothership_tag: "pledge"

url: "https://www.fightforthefuture.org/2017Pledge"
favicon: '/favicon.ico'
source: site

timezone: America/New_York
googleanalytics: UA-26576645-30

author:
  googleid: 102356128596404327231
  twitterid: 382376904
  twitter: fightfortheftr

#############
# Authoring #
#############

future: true
show_drafts: true
permalink: /:title/

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

#############
# Compiling #
#############

keep_files: ['images', 'css', 'js']

highlighter: rouge

gems: ['jekyll-redirect-from']
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]
